- name: Launch HTTPD proxy
  community.docker.docker_container:
    name: httpd
    image: guillaumebernardefrei/tp-devops-httpd:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: frontend-network
